"""empty message

Revision ID: 5a7dfb861209
Revises: b54188080240
Create Date: 2025-08-13 18:39:44.820983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a7dfb861209'
down_revision: Union[str, Sequence[str], None] = 'b54188080240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy_stock', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy_stock', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
