"""Remove subscribe column from user

Revision ID: 7b68a4e9f251
Revises: 4ffb748effb8
Create Date: 2025-08-10 01:00:22.511032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b68a4e9f251'
down_revision: Union[str, Sequence[str], None] = '4ffb748effb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy_stock', schema=None) as batch_op:
        batch_op.alter_column('toy_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy_stock', schema=None) as batch_op:
        batch_op.alter_column('toy_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)

    # ### end Alembic commands ###
