"""Add profile_image to user

Revision ID: 93b25d02d854
Revises: fc594b31faff
Create Date: 2025-08-09 16:44:44.340084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b25d02d854'
down_revision: Union[str, Sequence[str], None] = 'fc594b31faff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('toy_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.BigInteger(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('subscribe', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscribe')
        batch_op.drop_column('points')

    with op.batch_alter_table('toy_stock', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('donor_requests', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
