"""empty message

Revision ID: a4e6791e688f
Revises: ebc148466907
Create Date: 2025-08-18 18:06:54.083330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e6791e688f'
down_revision: Union[str, Sequence[str], None] = 'ebc148466907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('soil', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('damage', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy_stock', schema=None) as batch_op:
        batch_op.drop_column('damage')
        batch_op.drop_column('soil')
        batch_op.drop_column('material')

    # ### end Alembic commands ###
